
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate server JSON files
        run: |
          python -mjson.tool "servers_v8.json" > /dev/null
          python -mjson.tool "servers_be.json" > /dev/null
